version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  db_data:
