version: '3.1'

services:

  db:
    image: postgres:14-bullseye
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080