@startuml
left to right direction

class Player

class Court

class Booking

class Match {
  -player1: Player
  -player2: Player
  -score1: int
  -score2: int
  -court: Court
}

Player "*" -- "*" Court
(Player, Court) .. Booking
Match "*" --> "1" Player : Player1 >
Match "*" --> "1" Player : Player2 >
Match --> Court

'note "Das ist ein Kommentar" as CMT1
'CMT1 .right. Player

@enduml